# Generated by Django 5.0.1 on 2024-01-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_employee_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='state',
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='anil', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='9335543724', max_length=50),
        ),
    ]
